Settings:
  # Включить спрос на скачивание ресурс пака.
  Resourcepack: false
  # Прямая ссылка на скачивание ресурс пака.
  Link: ''
  # Сообщение получает клиент, который не согласился скачать ресурс пак.
  KickMessage:
    - ''
    - '&4Вы не установили Ресурс-Пак сервера!'
    - '&cСледуйте по инструкции:'
    - ''
    - '&fНастроить > Пакет ресурсов -> Включены'
    - ''
