Settings:
  Resourcepack: false
  Link: ''
  KickMessage:
    - ''
    - '&4Вы не установили Ресурс-Пак сервера!'
    - '&cСледуйте по инструкции:'
    - ''
    - '&fНастроить > Пакет ресурсов -> Включены'
    - ''
